const express = require('express');
const router = express.Router();
const managementController = require('../controllers/managementController');
router.get('/form-options', managementController.getFormOptions);
router.get('/employees', managementController.getEmployees);
router.get('/employees/:id', managementController.getEmployeeById);
router.put('/employees/:id', managementController.updateEmployee);
router.post('/employees', managementController.createEmployee);
router.delete('/employees/:id', managementController.deleteEmployee);
module.exports = router;